Add files via upload

diff --git a/usr/bin/sourceutility b/usr/bin/sourceutility
--- a/usr/bin/sourceutility
+++ b/usr/bin/sourceutility
@@ -1,13 +1,14 @@
 #!/bin/sh 
 
 clear
-VER="0.4-2"
+VER="0.4-3"
 echo "sourceutility v" $VER
 
 ## ----------------------------------
 # Step #1: Define variables
 # ----------------------------------
 RED='\033[31m'
+BLUE='\033[34m'
 STD='\033[0;0;39m'
 ROOT="/"
 SOURCEUTILITYDIR="/sourceutility"
@@ -28,6 +29,7 @@ CYDIAPREFSBACKUP="$CYDIAPREFSBACKUPDIR/$CYDIAPREFNAME"
 CYDIACACHEDIR="/private/var/mobile/Library/Caches/com.saurik.Cydia"
 CYDIASOURCESCACHE="$CYDIACACHEDIR/sources.list"
 CYDIALISTCACHE="$CYDIACACHEDIR/lists"
+CYDIAARCHIVES="$CYDIACACHEDIR/archives"
 CYDIACACHEBACKUPDIR="$SOURCEBACKUPDIR/cache"
 
 APTDIR="/private/var/lib/apt"
@@ -48,11 +50,34 @@ pause(){
 
 coming_soon(){ 
     read -p "This feature is coming soon. Press [Enter/Return] to continue" fackEnterKey 
-    }
+}
+check_if_root(){
+    if [[ $EUID -ne 0 ]]; then
+        echo "Please run this script as root!" 
+        exit 1
+    fi
+}
+kill_sileo(){
+    check_if_root
+    echo "Killing Sileo..."
+    killall Sileo
+}
+kill_cydia() {
+    check_if_root
+    echo "Killing Cydia..."
+    killall Cydia
+}
+decide_if_tip() {
+    if [ $(( ( RANDOM % 10 )  + 1 )) -gt 7 ]
+    then
+    echo "Tip: Entries with blue labels have menus behind them!"
+    echo ""
+    fi
+}
 
 init(){
-    if [ ! -w $ROOT ]
-    then
+        check_if_root
+    if [ ! -w $ROOT ]; then
 	# Root directory is not writeable
         echo -e "${RED}Cannot write to root directory. Try running as root?${STD}"
         pause
@@ -60,21 +85,18 @@ init(){
     fi
 
     # If the Source Utility Directory doesn't already exist, create one
-    if [ ! -d $SOURCEUTILITYDIR ]
-    then
+    if [ ! -d $SOURCEUTILITYDIR ]; then
         mkdir $SOURCEUTILITYDIR
         echo "Created sourceutility directory!"
     fi
 
     # If the Source Backup Directory doesn't already exist, create one
-    if [ ! -d  $SOURCEBACKUPDIR ]
-    then
+    if [ ! -d  $SOURCEBACKUPDIR ]; then
         mkdir $SOURCEBACKUPDIR
         echo "Created backup directory!" 
     fi
 
-    if [ ! -d $SOURCEUTILITYTMP ]
-    then
+    if [ ! -d $SOURCEUTILITYTMP ]; then
         mkdir $SOURCEUTILITYTMP
         echo "Created temp directory!"
     fi
@@ -93,17 +115,16 @@ remove_lists_sources() {
     echo -e "This is a dangerous procedure. You ${RED}will lose all Cydia & Sileo sources/lists${STD} after executing this."
     read -p "Are you sure you want to continue? [Y/N] " -n 1 -r
                         echo    # (optional) move to a new line
-                        if [[ $REPLY =~ ^[Yy]$ ]]
-                        then
+                        if [[ $REPLY =~ ^[Yy]$ ]]; then
                             read -p "Are you REALLY sure you want to continue? [Y/N] " -n 1 -r
                                 echo    # (optional) move to a new line
-                                if [[ $REPLY =~ ^[Yy]$ ]]
-                                then
+                                if [[ $REPLY =~ ^[Yy]$ ]]; then
                                     echo -e "Type '${RED}leavemealone${STD}' (ofc w/ out the quotes) and press enter to proceed:"
                                         read msg
 
-                                        if [ $msg = "leavemealone" ]
-                                        then
+                                        if [ $msg = "leavemealone" ]; then
+                                            kill_cydia
+                                            kill_sileo
                                             echo -e "${RED}Deleting target sources..."
                                             rm -rf $CYDIASOURCES
                                             echo -e "${RED}Deleting Cydia cache..."
@@ -134,15 +155,13 @@ remove_lists_sources() {
 }
 
 delete_source_backups(){
-    if [ ! -w $ROOT ]
-    then
+    if [ ! -w $ROOT ]; then
 	# Root directory is not writeable
         echo -e "${RED}Cannot write to root directory. Try running as root?${STD}"
         pause
         start_menu
     fi
-    if [ ! -w $SOURCEUTILITYDIR ]
-    then
+    if [ ! -w $SOURCEUTILITYDIR ]; then
 	# Root directory is not writeable
         echo -e "${RED}Cannot write to ${SOURCEUTILITYDIR}. Try running as root?${STD}"
         pause
@@ -150,16 +169,13 @@ delete_source_backups(){
     fi
     cd $SOURCEUTILITYDIR
     find . -name "*.zip" -type f -delete
-    if [ -d $SOURCEBACKUPDIR ]
-    then
+    if [ -d $SOURCEBACKUPDIR ]; then
         rm -rfv $SOURCEBACKUPDIR
     fi
-    if [ -d "$SOURCEUTILITY/sourceutility" ]
-    then
+    if [ -d "$SOURCEUTILITY/sourceutility" ]; then
         rm -rfv "$SOURCEUTILITY/sourceutility"
     fi
-    if [ -d "$SOURCEUTILITY/backupsources" ]
-    then
+    if [ -d "$SOURCEUTILITY/backupsources" ]; then
         rm -rfv "$SOURCEUTILITY/backsources"
     fi
 
@@ -175,13 +191,11 @@ init
 echo -e "It is important that you do ${RED}NOT${STD} terminate this script while you are backing up your sources."
         pause
 
-if [ -w $SOURCEBACKUPZIP ]
-then
+if [ -w $SOURCEBACKUPZIP ]; then
     echo -e "${RED}Backup from earlier today detected!${STD}"
     read -p "Would you like to remove this earlier backup? [Y/N] " -n 1 -r
         echo    # (optional) move to a new line
-        if [[ $REPLY =~ ^[Yy]$ ]]
-        then
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
         rm -rfv $SOURCEBACKUPZIP
         else
         echo "The older backup must be removed to continue. Returning to Start Menu..."
@@ -194,20 +208,17 @@ echo "Checking read permissions needed for backup..."
 
 {
 
-if [ ! -r $CYDIAPREFS ]
-then
+if [ ! -r $CYDIAPREFS ]; then
     echo "Cannot read $CYDIAPREFS. Try running as root?"
     pause
     start_menu
 fi
-if [ ! -r $CYDIACACHEDIR ]
-then
+if [ ! -r $CYDIACACHEDIR ]; then
     echo "Cannot read $CYDIACACHEDIR. Try running as root?"
     pause
     start_menu
 fi
-if [ ! -r $SOURCELISTS ]
-then
+if [ ! -r $SOURCELISTS ]; then
     echo "Cannot read $SOURCELISTS. Try running as root?"
     pause
     start_menu
@@ -226,18 +237,21 @@ mkdir $CYDIACACHEBACKUPDIR
 echo "Creating backup directory for Source Lists... (Sileo also stores its sources here)"
 mkdir $SOURCELISTSBACKUPDIR
 echo "Successfully created backup directories!" && sleep 2
+killall Cydia
+killall Sileo
 ## Copying files to backup dirs
 echo "Copying Cydia Preferences to $CYDIAPREFSBACKUPDIR..."
 cp -rfv $CYDIAPREFS $CYDIAPREFSBACKUPDIR
 echo "Copying Cydia Cache to $CYDIACACHEBACKUPDIR..."
 cp -rfv $CYDIASOURCESCACHE $CYDIACACHEBACKUPDIR
 cp -rfv $CYDIALISTCACHE $CYDIACACHEBACKUPDIR
+cp -rfv $CYDIAARCHIVES $CYDIACACHEBACKUPDIR
 echo "Copying Source Lists to $SOURCELISTSBACKUPDIR..."
 cp -afv "$SOURCELISTS/." "$SOURCELISTSBACKUPDIR/"
 echo "Successfully copied files to backup directories!" && sleep 2
 cd $SOURCEUTILITYDIR
 echo "Zipping backup files..."
-zip -r $SBZRELATIVE $SBDRELATIVE
+zip -r9 $SBZRELATIVE $SBDRELATIVE
 cd /
 echo "Cleaning up..."
 rm -rfv $SOURCEBACKUPDIR
@@ -264,13 +278,11 @@ restore_sources() {
                 BACKUPTOUNZIP="$SOURCEUTILITYDIR/sourcebackup-$backupDate.zip"
                 BTURELATIVE="./sourcebackup-$backupDate.zip"
 
-            if [[ "$backupDate" = 'exit' || "$backupDate" = 'leave' || "$backupDate" = "cancel" || "$backupDate" = "stop" ]]
-            then
+            if [[ "$backupDate" = 'exit' || "$backupDate" = 'leave' || "$backupDate" = "cancel" || "$backupDate" = "stop" ]]; then
             start_menu
             fi
 
-            if [ -w $BTURELATIVE ]
-            then
+            if [ -w $BTURELATIVE ]; then
                 
                 echo "Copying Backup to $SOURCEUTILITYTMP for contingency..."
                 cp -fv $BTURELATIVE $SOURCEUTILITYTMP
@@ -278,25 +290,24 @@ restore_sources() {
                 unzip -o ${BTURELATIVE}
                 echo "Unzipped!"
                 echo "Checking r/w permissions needed for restore..."
-                if [ ! -r $CYDIAPREFS ]
-                then
+                if [ ! -r $CYDIAPREFS ]; then
                     echo "Cannot read $CYDIAPREFS. Try running as root?"
                     pause
                     start_menu
                 fi
-                if [ ! -r $CYDIACACHEDIR ]
-                then
+                if [ ! -r $CYDIACACHEDIR ]; then
                     echo "Cannot read $CYDIACACHEDIR. Try running as root?"
                     pause
                     start_menu
                 fi
-                if [ ! -r $SOURCELISTS ]
-                then
+                if [ ! -r $SOURCELISTS ]; then
                     echo "Cannot read $SOURCELISTS. Try running as root?"
                     pause
                     start_menu
                 fi
                 echo "R/W permissions seem to be okay! Continuing with restore..." && sleep 2
+                kill_cydia
+                kill_sileo
                 ## Copying backup files to their respective locations
                 echo "Copying Cydia Preferences Backup to $PREFSDIR"
                 cp -fv $CYDIAPREFSBACKUP $PREFSDIR
@@ -308,8 +319,7 @@ restore_sources() {
                 rm -rfv $SOURCEBACKUPDIR
                 read -p "Would you like to delete the $BTURELATIVE? [Y/N] " -n 1 -r
                     echo    # (optional) move to a new line
-                    if [[ $REPLY =~ ^[Yy]$ ]]
-                    then
+                    if [[ $REPLY =~ ^[Yy]$ ]]; then
                         rm -fv $BTURELATIVE
                     fi
                 echo "If the backup did not restore correctly, you can open the zip file in $SOURCEUTILITYTMP"
@@ -341,7 +351,7 @@ restore_sources() {
                 chown 0:0 /Applications/Cydia.app/Cydia
                 echo "Patched!" && sleep 2
                 kill_springboard
-                exit 0;;
+                start_menu
 
             else 
             echo "Could not read $BTURELATIVE. Does it exist?"
@@ -355,8 +365,7 @@ restore_sources() {
     start_menu
 }
 purge_ds_store() {
-    if [ ! -w $ROOT ]
-    then
+    if [ ! -w $ROOT ]; then
         # Root directory is not writeable
         echo -e "${RED}Cannot write to root directory. Try running as root?${STD}"
         pause
@@ -376,12 +385,14 @@ sync_sileo_to_cydia() {
 }
 
 hard_respring() {
+    check_if_root
     echo "Do NOT close terminate this script until your iOS Device has resprung."
     echo "Respringing..."
     ldrestart
     exit 0;
 }
 kill_springboard() {
+    check_if_root
     echo "Killing springboard..." && sleep 1
     killall SpringBoard
     exit 0;
@@ -390,14 +401,14 @@ run_reboot() {
     echo -e "You are about to reboot your iOS Device. If you are runnning anything ${RED}newer than iOS 9.1${STD}, you are likely using an semi-tethered jailbreak. This means that after a reboot, you will ${RED}temporarily lose your jailbreak${STD}."
     read -p "Are you sure you want to continue? [Y/N] " -n 1 -r
         echo    # (optional) move to a new line
-        if [[ $REPLY =~ ^[Yy]$ ]]
-        then
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
             reboot
         else
         start_menu
         fi
 }
 convert_legacy_backups() {
+    check_if_root
     echo -e "Legacy Backups are backups made with sourcebackup v0.1 and sourceutility <=0.2-2."
     pause
     echo -e "Legacy Backups, although no longer supported, can still be made by installing sourceutility v0.2-2 or by running sourceutility-legacy ."
@@ -409,8 +420,7 @@ convert_legacy_backups() {
     pause
     read -p "If you wish to continue please press [Y/y] " -n 1 -r
         echo    # (optional) move to a new line
-        if [[ $REPLY =~ ^[Yy]$ ]]
-        then
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
         # Start of legacy conversion process
 
             if [ -d $SOURCEBACKUPDIR ]
@@ -427,9 +437,8 @@ convert_legacy_backups() {
                     fi
             fi
 
-            if [ -d "${sourceutility}/backupsources" ]
-            then
-                rm -rfv "${sourceutility}/backupsources"
+            if [ -d "${SOURCEUTILITYDIR}/backupsources" ]; then
+                rm -rfv "${SOURCEUTILITYDIR}/backupsources"
                 clear
             fi
 
@@ -445,13 +454,11 @@ convert_legacy_backups() {
                 CONVERTEDBACKUP="./sourcebackup-$backupDate.zip"
                 
 
-            if [[ "$backupDate" = 'exit' || "$backupDate" = 'leave' || "$backupDate" = "cancel" || "$backupDate" = "stop" ]]
-            then
+            if [[ "$backupDate" = 'exit' || "$backupDate" = 'leave' || "$backupDate" = "cancel" || "$backupDate" = "stop" ]]; then
             start_menu
             fi
 
-            if [ -w $BACKUPTOUNZIP ]
-            then
+            if [ -w $BACKUPTOUNZIP ]; then
                 echo "Copying $BACKUPTOUNZIP to tmp directory for contingency..."
                 cp -r $BACKUPTOUNZIP $SOURCEUTILITYTMP
                 echo "Making directory for Legacy Backup..."
@@ -468,7 +475,7 @@ convert_legacy_backups() {
                 cp -fv "./backupsources/cydia/com.saurik.Cydia.plist" $CYDIAPREFSBACKUPDIR
                 cp -afv "./backupsources/sileo/." $SOURCELISTSBACKUPDIR
                 echo "Zipping newly converted backup..."
-                zip -r $CONVERTEDBACKUP $SBDRELATIVE
+                zip -r9 $CONVERTEDBACKUP $SBDRELATIVE
                 echo "Cleaning up..."
                 rm -rfv "./backupsources"
                 rm -rfv "./legacy_backup"
@@ -499,6 +506,7 @@ show_menus() {
 	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"	
 	echo " sourceutility ${VER} by TheHacker "
     echo ""
+    decide_if_tip
     echo "~~ Start Menu ~~"
 	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 	echo "1. Backup Cydia and/or Sileo Sources"
@@ -507,7 +515,7 @@ show_menus() {
     echo "4. Convert Legacy Backups"
 	echo "5. Sync Cydia Sources to Sileo"
     echo "6. Sync Sileo Sources to Cydia"
-    echo "7. Utilities Menu"
+    echo -e "7. ${BLUE}Utilities Menu${STD}"
 	echo "0. Exit"
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 }
@@ -567,15 +575,16 @@ show_u_menus() {
 	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"	
 	echo " sourceutility ${VER} by TheHacker "
     echo ""
+    decide_if_tip
     echo "~~ Other Utilities Menu ~~"
 	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 	echo "1. ldrestart"
-    echo "2. Kill Springboard"
+    echo -e "2. ${BLUE}Kill${STD}"
     echo -e "3. ${RED}Reboot${STD}"
     echo "4. Purge .DS_STORE files"
     echo -e "5. ${RED}Purge Cydia & Sources Lists/Sources${STD}"
     echo "6. apt-get update"
-    echo "7. Start Menu"
+    echo -e "7. ${BLUE}Start Menu${STD}"
     echo "0. Exit"
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 }
@@ -589,37 +598,51 @@ read_u_options(){
             } || { 
                 echo -e "${RED}Could not run ldrestart. Try running as root?${STD}" && sleep 2
                 } ;;
-        2) {
-            kill_springboard
-            } || {
-                echo -e "${RED}Could not kill springboard. Try running as root?${STD}" && sleep 2
-            } ;;
+        2) kill_menu ;;
         3) {
             run_reboot
             } || {
                 echo -e "${RED}Could not reboot. Try running as root?${STD}" && sleep 2
             } ;;
-        4) {
-            purge_ds_store
-            } || {
-                exit 1;
-            } ;;
-        
-		5) {
-            remove_lists_sources 
-            } || {
-                exit 1;
-            } ;;
-        6) {
-        update_sources
-        } || {
-            exit 1;
-        } ;;
-		7) {
-            start_menu
-            } || {
-                exit 1;
-            } ;;
+        4) purge_ds_store ;;
+		5) remove_lists_sources ;;
+        6) update_sources ;;
+		7) start_menu ;;
+        0) exit 0;;
+		*) echo -e "${RED}Invalid Option...${STD}" && sleep 2
+	esac
+}
+show_kill_menu() {
+    clear
+    echo ""
+    echo ""
+	echo ""
+    echo ""
+    echo ""
+    echo ""
+	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"	
+	echo " sourceutility ${VER} by TheHacker "
+    echo ""
+    decide_if_tip
+    echo "~~ Kill Menu ~~"
+	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+	echo "1. Kill Springboard"
+    echo "2. Kill Cydia"
+    echo "3. Kill Sileo"
+    echo -e "4. ${BLUE}Start Menu${STD}"
+    echo -e "5. ${BLUE}Utilities Menu${STD}"
+    echo "0. Exit"
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+}
+read_kill_options() {
+    local choice
+	read -p "Enter choice [ 0 - 5 ] " choice
+	case $choice in
+		1) kill_springboard ;;
+        2) kill_cydia ;;
+        3) kill_sileo ;;
+		4) start_menu ;;
+        5) utilies_menu ;;
         0) exit 0;;
 		*) echo -e "${RED}Invalid Option...${STD}" && sleep 2
 	esac
@@ -643,6 +666,11 @@ utilies_menu() {
     cd /
     show_u_menus
     read_u_options
+}
+kill_menu() {
+    cd /
+    show_kill_menu
+    read_kill_options
 }
 while true
 do
